#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
modlibs:
	(cd Wi-Fi_MQTT_Client; make modlibs)
.PHONY: modlibs

library-manager:
	(cd Wi-Fi_MQTT_Client; make library-manager)
.PHONY: library-manager

qspi-configurator:
	(cd Wi-Fi_MQTT_Client; make qspi-configurator)
.PHONY: qspi-configurator

config:
	(cd Wi-Fi_MQTT_Client; make config)
.PHONY: config

device-configurator:
	(cd Wi-Fi_MQTT_Client; make device-configurator)
.PHONY: device-configurator

capsense-configurator:
	(cd Wi-Fi_MQTT_Client; make capsense-configurator)
.PHONY: capsense-configurator

capsense-tuner:
	(cd Wi-Fi_MQTT_Client; make capsense-tuner)
.PHONY: capsense-tuner

seglcd-configurator:
	(cd Wi-Fi_MQTT_Client; make seglcd-configurator)
.PHONY: seglcd-configurator

bsp-assistant:
	(cd Wi-Fi_MQTT_Client; make bsp-assistant)
.PHONY: bsp-assistant

config_bt:
	(cd Wi-Fi_MQTT_Client; make config_bt)
.PHONY: config_bt

bt-configurator:
	(cd Wi-Fi_MQTT_Client; make bt-configurator)
.PHONY: bt-configurator

config_usbdev:
	(cd Wi-Fi_MQTT_Client; make config_usbdev)
.PHONY: config_usbdev

usbdev-configurator:
	(cd Wi-Fi_MQTT_Client; make usbdev-configurator)
.PHONY: usbdev-configurator

smartio-configurator:
	(cd Wi-Fi_MQTT_Client; make smartio-configurator)
.PHONY: smartio-configurator

config_ezpd:
	(cd Wi-Fi_MQTT_Client; make config_ezpd)
.PHONY: config_ezpd

ez-pd-configurator:
	(cd Wi-Fi_MQTT_Client; make ez-pd-configurator)
.PHONY: ez-pd-configurator

config_lin:
	(cd Wi-Fi_MQTT_Client; make config_lin)
.PHONY: config_lin

lin-configurator:
	(cd Wi-Fi_MQTT_Client; make lin-configurator)
.PHONY: lin-configurator

